<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <EnableNETAnalyzers>false</EnableNETAnalyzers>
        <EnforceCodeStyleInBuild>false</EnforceCodeStyleInBuild>
        <NoWarn>xUnit1051</NoWarn>
    </PropertyGroup>

    <ItemGroup>
        <AssemblyAttribute Include="System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\Wiknap.Email\Wiknap.Email.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Bogus"/>
        <PackageReference Include="Microsoft.NET.Test.Sdk"/>
        <PackageReference Include="Microsoft.Testing.Extensions.VSTestBridge" />
        <PackageReference Include="NSubstitute"/>
        <PackageReference Include="Shouldly"/>
        <PackageReference Include="xunit.runner.visualstudio">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="xunit.v3"/>
    </ItemGroup>
</Project>
